### ISSUE TITLE
Pneumatic craft Progression Deadlocked at Amadron Tablet

### ISSUE THREAD

**Issue by z64555** [Electrofried/ModColonies#12]
Gov found this last night, and maybe redcatone before that if I remember correctly.

Essentially, it's currently impossible to progress through Pneumatic craft because the UV lightbox needs a blueprint which can only be bought on Amadron.  However, the recipe for the Amadron Tablet crafts it as empty, meaning you need the Charging Station to Charge the Amadron Tablet so you can buy the blueprint to make PCB's so you can unlock the Charging Station...

Anyway, suggested fix is to either alter the recipe of the Tablet to have it pre-charged, or change the research requirements to something that's achievable (maybe empty PCB's?) Or maybe add a recipe in the pressure chamber to charge the tablet, air cans, and other tools.

![2021-06-08_08 51 06](https://user-images.githubusercontent.com/5084344/121197799-3ac9eb00-c837-11eb-8e69-2f58ed4c9eb2.png)

**Comment by wrincewind** [comment]
2 solutions spring to mind here. 1 is to make the PCB blueprint a craftable item, or to make the Lightbox not require it (perhaps substituting a block of emerald to keep the cost roughly equivalent to the intended method). Another option would be to change the Amadron Tablet so that it comes with a full tank of air when crafted - but that runs the risk of the player emptying it before buying what they need.

**Comment by Electrofried** [comment]
Fixed in dev
